---
title: "R Notebook"
output: html_notebook
---

## Load libraries and data
```{r}
library('ggplot2') # visualization
library('ggthemes') # visualization
library('scales') # visualization
library('dplyr') # data manipulation
library('mice') # imputation
library('randomForest') # classification algorithm
```

```{r}
train <- read.csv("../data/train.csv", stringsAsFactors = F)
test <- read.csv("../data/test.csv", stringsAsFactors = F)
gender <- read.csv("../data/gender_submission.csv", stringsAsFactors = F)
all_data <- bind_rows(train, test)

str(train)
str(test)
```

## Feature engineering
```{r}
all_data$Title <- gsub("(.*, )|(\\..*)", "", all_data$Name)

table(all_data$Sex, all_data$Title)

rare_title <- c("Dona", "Dr", "Lady", "the Countess", "Capt", "Col", "Don", "Jonkheer", "Major","Sir", "Rev")

all_data$Title[all_data$Title == "Mme"] <- "Miss"
all_data$Title[all_data$Title == "Mlle"] <- "Miss"
all_data$Title[all_data$Title == "Ms"] <- "Miss"
all_data$Title[all_data$Title %in% rare_title] <- "Rare Title"

table(all_data$Sex, all_data$Title)

all_data$Surname <- sapply(all_data$Name, 
                           function(x){strsplit(x,"[,.]")[[1]][1]})

all_data$Fsize <- all_data$SibSp + all_data$Parch + 1

all_data$Family <- paste(all_data$Surname, all_data$Fsize, sep = "_")

ggplot(all_data[1:891,], aes(x = Fsize, fill = factor(Survived))) +
  geom_bar(stat = "count", position = "dodge") +
  scale_x_continuous(breaks = c(1:11)) +
  labs(x = "Family Size") + 
  theme_few()

all_data$FsizeD[all_data$Fsize == 1] <- "Singleton"
all_data$FsizeD[all_data$Fsize < 5 & all_data$Fsize > 1] <- "Small"
all_data$FsizeD[all_data$Fsize > 4] <- "Large"

mosaicplot(table(all_data$FsizeD, all_data$Survived), main = "Family Size by Survival", shade = TRUE)
```

```{r}
all_data$Deck <- factor(sapply(all_data$Cabin, 
                        function(x){strsplit(x, NULL)[[1]][1]}))

```

## Missing data
```{r}
embark_fare <- all_data %>% 
  filter(PassengerId != 62 & PassengerId != 830)

ggplot(embark_fare, aes(x = Embarked, y = Fare, fill = factor(Pclass))) +
  geom_boxplot() +
  geom_hline(aes(yintercept = 80), color = "red", linetype = "dashed", lwd = 2) + 
  scale_y_continuous(labels = dollar_format()) +
  theme_few()

all_data$Embarked[c(62, 830)] <- "c"

ggplot(all_data[all_data$Pclass == '3' & all_data$Embarked == 'S', ], 
  aes(x = Fare)) +
  geom_density(fill = '#99d6ff', alpha=0.4) + 
  geom_vline(aes(xintercept=median(Fare, na.rm=T)),
    colour='red', linetype='dashed', lwd=1) +
  scale_x_continuous(labels=dollar_format()) +
  theme_few()

all_data$Fare[1044] <- median(all_data[all_data$Pclass == "3" && all_data$Embarked == "S",]$Fare, na.rm = TRUE)
```

```{r}
factor_vars <- c('PassengerId','Pclass','Sex','Embarked',
                 'Title','Surname','Family','FsizeD')
all_data[factor_vars] <- lapply(all_data[factor_vars], function(x) as.factor(x))

set.seed(129)

mice_mode <- mice(all_data[, !names(all_data) %in% c('PassengerId','Name','Ticket','Cabin','Family','Surname','Survived')], method = "rf")
mice_output <- complete(mice_mode)

par(mfrow=c(1,2))
hist(all_data$Age, freq=F, main='Age: Original Data', 
  col='darkgreen', ylim=c(0,0.04))
hist(mice_output$Age, freq=F, main='Age: MICE Output', 
  col='lightgreen', ylim=c(0,0.04))

all_data$Age <- mice_output$Age
```

## Feature engineering 2 round
```{r}
ggplot(all_data[1:891,], aes(Age, fill = factor(Survived))) + 
  geom_histogram() + 
  facet_grid(.~Sex) + 
  theme_few()

all_data$Child[all_data$Age < 18] <- 'Child'
all_data$Child[all_data$Age >= 18] <- 'Adult'
table(all_data$Survived, all_data$Child)

all_data$Mother <- 'Not Mother'
all_data$Mother[all_data$Sex == 'female' & all_data$Parch > 0 & all_data$Age > 18 & all_data$Title != 'Miss'] <- 'Mother'
table(all_data$Mother, all_data$Survived)
all_data$Child  <- factor(all_data$Child)
all_data$Mother <- factor(all_data$Mother)

md.pattern(all_data)
```

## Prediction
```{r}
train <- all_data[1:891,]
test <- all_data[892:1309,]
```

```{r}
set.seed(754)
rf_model <- randomForest(factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + 
                                            Fare + Embarked + Title + 
                                            FsizeD + Child + Mother,
                                            data = train)
plot(rf_model, ylim=c(0,0.36))
legend('topright', colnames(rf_model$err.rate), col=1:3, fill=1:3)
```
```{r}
importance    <- importance(rf_model)
varImportance <- data.frame(Variables = row.names(importance), 
                            Importance = round(importance[ ,'MeanDecreaseGini'],2))
rankImportance <- varImportance %>%
  mutate(Rank = paste0('#',dense_rank(desc(Importance))))

ggplot(rankImportance, aes(x = reorder(Variables, Importance), 
    y = Importance, fill = Importance)) +
  geom_bar(stat='identity') + 
  geom_text(aes(x = Variables, y = 0.5, label = Rank),
    hjust=0, vjust=0.55, size = 4, colour = 'red') +
  labs(x = 'Variables') +
  coord_flip() + 
  theme_few()
```

```{r}
prediction <- predict(rf_model, test)
solution <- data.frame(PassengerID = test$PassengerId, Survived = prediction)

write.csv(solution, file = 'rf_mod_Solution.csv', row.names = F)
```

# SVM model
```{r}
library(e1071)
svm_model <- svm(factor(Survived) ~ Pclass + Sex + Age + SibSp + Parch + 
                                            Fare + Embarked + Title + 
                                            FsizeD + Child + Mother,
                                            data = train,
                                            kernel = "linear",cost = 10)
svm_pred <- predict(svm_model, test[,c("Pclass","Sex", "Age", "SibSp","Parch","Fare","Embarked","Title","FsizeD","Child","Mother")])
svm_sol <- data.frame(PassengerID = test$PassengerId, Survived = svm_pred)
write.csv(svm_sol, file = "svm_mod_Solution.csv", row.names = F)
```


